github:
  release: true
git:
  tagname: "${version}"
  push: true 
hooks:
  "after:git:release": "echo Git repo pushed remotely, now working on github release"
  "after:release": "echo Successfully released ${name} version ${version} to ${repo.repository}."

