version: '3.7'
services:

  php:
    image: registry.gitlab.com/opencontent/ezpublish/php
    restart: unless-stopped
    depends_on:
      - postgres
      - solr
    environment:
      EZ_ROOT: /var/www/html
      EZINI_file__eZDFSClusteringSettings__DBHost: postgres
      EZINI_file__eZDFSClusteringSettings__DBPort: 5432
      EZINI_file__eZDFSClusteringSettings__DBUser: ez
      EZINI_file__eZDFSClusteringSettings__DBPassword: verygoodsecret
      EZINI_file__eZDFSClusteringSettings__DBName: ezpublish
      EZINI_file__eZDFSClusteringSettings__MountPointPath: '/mnt/efs/cluster-openpa'
      EZINI_solr__SolrBase__SearchServerURI: 'http://solr:8983/solr/prototipo'
      EZINI_site__DatabaseSettings__Server: postgres
      EZINI_site__DatabaseSettings__Port: 5432
      EZINI_site__DatabaseSettings__User: ez 
      EZINI_site__DatabaseSettings__Password: verygoodsecret
      EZINI_site__DatabaseSettings__Database: ezpublish
      EZINI_site__FileSettings__VarDir: var/prototipo
      EZINI_site__SiteSettings__SiteName: "Prototipo"
      # the url is used only in email to make valid links
      EZINI_site__SiteSettings__SiteURL: "ezpublish.localtest.me"


  nginx:
    image: registry.gitlab.com/opencontent/ezpublish/nginx
    restart: unless-stopped
    labels:
      traefik.frontend.rule: 'Host:ezpublish.localtest.me'
    depends_on:
      - php

  varnish:
    image: wodby/varnish
    restart: unless-stopped
    depends_on:
      - nginx
    environment:
      VARNISH_BACKEND_GRACE: 10m
      VARNISH_BACKEND_HOST: nginx
      VARNISH_CACHE_STATIC_FILES: 1
      VARNISH_DEFAULT_TTL: 300s
      VARNISH_ERRORS_GRACE: 60s

  solr:
    image: 'registry.gitlab.com/opencontent/solr:4.10.4'
    command: '-s /opt/ez'
    restart: unless-stopped
    volumes:
      - './conf.d/solr:/opt/ez/'
    # FixMe: must be enabled in config: https://stackoverflow.com/questions/19248746/configure-health-check-in-solr-4
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "localhost:7983/solr/prototipo/admin/ping"]

  postgres:
    image: 'postgres:9.6-alpine'
    restart: unless-stopped
    labels:
      traefik.enable: false
    environment:
      POSTGRES_DB: ezpublish
      POSTGRES_USER: ez
      POSTGRES_PASSWORD: verygoodsecret
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
      - 'pgdata:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --user ez --dbname ezpublish"]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: registry.gitlab.com/opencontent/traefik-localtestme:latest 
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  html:
  dfs:
  solrdata:
  pgdata:
