FROM nginx:1.17.8-alpine

RUN apk add --no-cache bash httpie

RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

COPY conf.d/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf.d/nginx/nginx-vhost.conf /etc/nginx/conf.d/default.conf
COPY conf.d/nginx/docker-entrypoint.sh /docker-entrypoint.sh

HEALTHCHECK --interval=1m --timeout=3s \
  CMD http localhost/nginx_status

CMD [ "/docker-entrypoint.sh" ]
